# Generated by Django 5.1.7 on 2025-03-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IS335APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ride",
            table="rides",
        ),
        migrations.AlterModelTable(
            name="rider",
            table="rider",
        ),
    ]
