# Generated by Django 5.1.7 on 2025-03-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IS335APP", "0002_alter_ride_table_alter_rider_table"),
    ]

    operations = []
